#!/usr/bin/env sh
#
# Run code style linters and tests on the continuous integration server.
#
# NOTE: the script does not rely on Docker.
#
# Examples
#
#   script/cibuild
set -o errexit

cd "$(dirname "$0")/.."

echo "==> Checking the code style…"
rubocop --display-cop-names \
        --display-style-guide \
        --extra-details \
        --fail-fast \
        --config=.rubocop.yml

echo "==> Starting tests…"
bin/rails test test

