#!/usr/bin/env sh
#
# Launch a console for the application.
#
# Examples
#
#   script/console
set -o errexit

cd "$(dirname "$0")/.."

if which docker-compose > /dev/null
then
  docker-compose run --rm \
                     web "$0" "$@"
  exit 0
fi

bin/rails console
