#!/usr/bin/env sh
#
# Deploy the application.
#
# Examples
#
#   script/deploy
set -o errexit

cd "$(dirname "$0")/.."

echo "==> Updating the Docker image…"
docker build --tag rubyjobsru/app:latest .
docker push rubyjobsru/app

echo "==> Redeploying the service…"
docker-cloud service redeploy web
