#!/usr/bin/env sh
#
# Ensure code conforms the common style.
#
# Examples
#
#   script/lint
set -o errexit

cd "$(dirname "$0")/.."

if which docker-compose > /dev/null
then
  docker-compose run --no-deps \
                     --rm \
                     web "$0" "$@"
  exit 0
fi

echo "==> Checking the code style…"
rubocop --display-cop-names \
        --display-style-guide \
        --extra-details \
        --parallel \
        --config=.rubocop.yml \
        "${1:-.}"
