#!/usr/bin/env sh
#
# Launch the application and any extra required processes locally.
#
# Examples
#
#   script/server
set -o errexit

cd "$(dirname "$0")/.."

if which docker-compose > /dev/null
then
  docker-compose up
  exit 0
else
  echo "Sorry, '$0' cannot be called inside a Docker container."
  exit 1
fi
