#!/bin/sh
#
# Set up application for the first time after cloning, or set it
# back to the initial first unused state.
#
# Examples
#
#   script/setup
set -o errexit

cd "$(dirname "$0")/.."

if which docker-compose > /dev/null
then
  script/bootstrap

  echo "==> Preparing the development environment…"
  docker-compose build
  docker-compose run --rm \
                     web "$0"

  echo "==> Preparing the test environment…"
  docker-compose --project-name=app-test build
  docker-compose --project-name=app-test \
                 --file=docker-compose.yml \
                 --file=docker-compose.test.yml \
                 run --rm \
                     web "$0"
  exit 0
fi

echo "==> Preparing the database…"
bin/rake db:reset
