#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Setting up DB…"

# Reset development and test databases to a fresh state.
foreman run bin/rake db:reset
foreman run --env=.env.test bin/rake db:reset

echo "==> App is now ready to go!"
