#!/usr/bin/env sh
#
# Run system test suite for application. Optionally pass in a path to an
# individual test file to run a single test.
#
# Examples
#
#   script/system_test [<FILE>]
#
# <FILE> - the path to a spec file.
set -o errexit

cd "$(dirname "$0")/.."

if which docker-compose > /dev/null
then
  docker-compose --project-name=app-test \
                 --file=docker-compose.yml \
                 --file=docker-compose.test.yml \
                 run --rm \
                     system_test_runner "$0" "$@"

  exit 0
fi

echo "==> Starting system tests…"
bin/rails test "${1:-test/system}"
