#!/usr/bin/env sh
#
# Run test suite for application. Optionally pass in a path to an individual
# test file to run a single test.
#
# Examples
#
#   script/test [<FILE>]
#
# <FILE> - the path to a spec file.
set -o errexit

cd "$(dirname "$0")/.."

if which docker-compose > /dev/null
then
  docker-compose --project-name=app-test \
                 --file=docker-compose.yml \
                 --file=docker-compose.test.yml \
                 run --rm \
                     web "$0" "$@"

  exit 0
fi

echo "==> Starting tests…"
rspec --color \
      "${1:-spec}"
