#!/usr/bin/env sh
#
# Update application to run for its current checkout.
#
# Examples
#
#   script/update
set -o errexit

cd "$(dirname "$0")/.."

if which docker-compose > /dev/null
then
  docker build --tag rubyjobsru/app:latest .
  script/bootstrap

  echo "==> Updating the development environment…"
  docker-compose run --rm \
                     web "$0"

  echo "==> Updating the test environment…"
  docker-compose --project-name=app-test \
                 --file=docker-compose.yml \
                 --file=docker-compose.test.yml \
                 run --rm \
                     web "$0"
  exit 0
fi

echo "==> Updating the database…"
rake db:schema:load
